export default {
    //Healthsight列表功能
    HEALTHSIGHT_REFRESH:'HEALTHSIGHT_REFRESH',//下拉刷新中
    HEALTHSIGHT_LOAD_FAILED:'HEALTHSIGHT_LOAD_FAILED',//下拉刷新失败
    HEALTHSIGHT_LOAD_SUCCESSFUL:'HEALTHSIGHT_LOAD_SUCCESSFUL',//下拉刷新成功
    HEALTHSIGHT_LOAD_MORE_FAILED:'HEALTHSIGHT_LOAD_MORE_FAILED',//上拉加载失败
    HEALTHSIGHT_LOAD_MORE_SUCCESSFUL:'HEALTHSIGHT_LOAD_MORE_SUCCESSFUL',//上拉加载成功
    //DoctorcureList列表功能
    DOCTORCURE_LIST_REFRESH:'DOCTORCURE_LIST_REFRESH',//下拉刷新中
    DOCTORCURE_LIST_LOAD_FAILED:'DOCTORCURE_LIST_LOAD_FAILED',//下拉刷新失败
    DOCTORCURE_LIST_LOAD_SUCCESSFUL:'DOCTORCURE_LIST_LOAD_SUCCESSFUL',//下拉刷新成功
    DOCTORCURE_LIST_LOAD_MORE_FAILED:'DOCTORCURE_LIST_LOAD_MORE_FAILED',//上拉加载失败
    DOCTORCURE_LIST_LOAD_MORE_SUCCESSFUL:'DOCTORCURE_LIST_LOAD_MORE_SUCCESSFUL',//上拉加载成功
}