export default {
    HEALTHSIGHT_REFRESH:'HEALTHSIGHT_REFRESH',//下拉刷新中
    HEALTHSIGHT_LOAD_FAILED:'HEALTHSIGHT_LOAD_FAILED',//下拉刷新失败
    HEALTHSIGHT_LOAD_SUCCESSFUL:'HEALTHSIGHT_LOAD_SUCCESSFUL',//下拉刷新成功
    HEALTHSIGHT_LOAD_MORE_FAILED:'HEALTHSIGHT_LOAD_MORE_FAILED',//上拉加载失败
    HEALTHSIGHT_LOAD_MORE_SUCCESSFUL:'HEALTHSIGHT_LOAD_MORE_SUCCESSFUL',//上拉加载成功
}